# Generated by Django 6.0 on 2025-12-26 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('info', models.TextField(null=True)),
            ],
            options={
                'db_table': 'ui_ovpn_user',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('revoked', 'Revoked'), ('deleted', 'Deleted')], default='active', max_length=10)),
                ('account_number', models.CharField(max_length=100, unique=True)),
                ('expiration_date', models.DateField()),
                ('remaining_days', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openvpn_dashboard.user')),
            ],
            options={
                'db_table': 'ui_ovpn_account',
            },
        ),
    ]
