# Generated by Django 6.0 on 2025-12-28 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openvpn_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='total_bytes_received',
            field=models.BigIntegerField(default=0, help_text='Total bytes received (download) - cumulative'),
        ),
        migrations.AddField(
            model_name='account',
            name='total_bytes_sent',
            field=models.BigIntegerField(default=0, help_text='Total bytes sent (upload) - cumulative'),
        ),
        migrations.AddField(
            model_name='account',
            name='usage_last_updated',
            field=models.DateTimeField(blank=True, help_text='Last time usage was updated', null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='usage_reset_at',
            field=models.DateTimeField(blank=True, help_text='Last time usage was reset', null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('revoked', 'Revoked'), ('deleted', 'Deleted'), ('expired', 'Expired')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ConnectionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_address', models.CharField(help_text="Client's real IP:port", max_length=50)),
                ('virtual_address', models.CharField(blank=True, help_text='Assigned VPN IP', max_length=50, null=True)),
                ('connected_at', models.DateTimeField(help_text='When the client connected')),
                ('disconnected_at', models.DateTimeField(blank=True, help_text='When the client disconnected', null=True)),
                ('bytes_sent', models.BigIntegerField(default=0)),
                ('bytes_received', models.BigIntegerField(default=0)),
                ('last_bytes_sent', models.BigIntegerField(default=0)),
                ('last_bytes_received', models.BigIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('usage_committed', models.BooleanField(default=False, help_text='Whether usage has been added to account totals')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='openvpn_dashboard.account')),
            ],
            options={
                'db_table': 'ui_ovpn_connectionsession',
                'ordering': ['-connected_at'],
                'indexes': [models.Index(fields=['account', 'is_active'], name='ui_ovpn_con_account_d92336_idx'), models.Index(fields=['is_active', 'usage_committed'], name='ui_ovpn_con_is_acti_d3bf1d_idx')],
            },
        ),
    ]
